##############################################################################
#
# Copyright (c) 2008-2010 Terapix Youpi development team. All Rights Reserved.
#                    Mathias Monnerville <monnerville@iap.fr>
#                    Gregory Semah <semah@iap.fr>
#
# This program is Free Software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
##############################################################################

"""
Classes to generate PDF reports
"""

import types, time
import string, os.path
#
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.lib.pagesizes import A4

class PDFReport(object):
	width, height = A4
	margin = cm
	# Margins
	width, height = (width-2*margin, height-2*margin)

	def __init__(self, outfile, user, name = 'Report name', landscape = False):
		self.canvas = canvas.Canvas(outfile, pagesize = A4)
		if landscape:
			self.canvas.rotate(90)
			tmp = self.height
			self.height = self.width
			self.width = tmp
			self.canvas.translate(self.margin, -self.height-self.margin)
		else:
			self.canvas.translate(self.margin, self.margin)

		self.name = name
		self.user = user
		self.header_params = {'generated': "Generated by %s on %s" % (user.username, time.ctime()), 'toto': 'TRUC'}
		self.__write_header()

	
	def save(self):
		self.canvas.save()

	def __write_header(self):
		self.canvas.setStrokeColorRGB(0.3, 0.3, 0.3)
		self.canvas.setFillColorRGB(0, 0, 0)
		self.canvas.rect(0, self.height-0.6*cm, self.width, 0.05*cm, fill = 1)
		self.canvas.setFont("Times-Roman", 14)
		self.canvas.drawString(0, self.height-0.4*cm, self.name)
		y = self.height-cm
		self.canvas.setFont("Times-Roman", 10)
		for name, val in self.header_params.iteritems():
			self.canvas.drawString(0, y, val)
			y -= 0.4*cm
		self.canvas.showPage()

